### ISSUE TITLE
automatic delete on CopyToDevice

### ISSUE THREAD

**Issue by te42kyfo** [hughperkins/OpenCLHelper#1]
In CLArrayFloat::CopyToDevice, I wonder wether it is a good idea instead of asserting that the array is present on the host and not on the device to just delete it if is present on the device:
```C
     void copyToDevice() {
-        assert( onHost && !onDevice );
+        assert( onHost );
+               if( onDevice ) {
+                       deleteFromDevice();
+               }
         devicearray = clCreateBuffer(openclhelper->context, CL_MEM_READ_WRITE | CL_MEM_COPY_HOST_PTR, sizeof(float) * N, (void *)hostarray, &error);
```

Or is there a reason that is a bad idea? Or a more clever way to do it?

**Comment by te42kyfo** [comment]
That looks good. So you added implicit transfers between host and device? I think that would have worked in the scenario that I had. Nice to see some activity, I will consider your code again for future projects.

**Comment by hughperkins** [comment]
Cool.  Thanks :-)  I will close the issue.
